CREATE DATABASE ATIVIDADE1;
USE ATIVIDADE1;

CREATE TABLE EMPRESA
(
	ID_EMPRESA INT PRIMARY KEY AUTO_INCREMENT,
    NOME_EMPRESA VARCHAR(100) NOT NULL,
    ENDERECO VARCHAR(200) NOT NULL
);

CREATE TABLE PROJETO
(
	ID_PROJETO INT PRIMARY KEY AUTO_INCREMENT,
    DATA_INICIO DATE NOT NULL,
    DATA_TERMINO DATE NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    ID_EMPRESA INT NOT NULL,
    FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA)
);


CREATE TABLE CONSULTOR
(
	ID_CONSULTOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    RG VARCHAR(15) UNIQUE NOT NULL,
    ESPECIALIZACAO VARCHAR(20) NOT NULL
);

CREATE TABLE PARTICIPOU
(
	ID_PARTICIPOU INT PRIMARY KEY AUTO_INCREMENT,
    HORAS_TRABALHADAS TIME NOT NULL,
    FUNCAO VARCHAR(20) NOT NULL,
    ID_CONSULTOR INT NOT NULL,
    ID_PROJETO INT NOT NULL,
    FOREIGN KEY(ID_CONSULTOR) REFERENCES CONSULTOR(ID_CONSULTOR),
    FOREIGN KEY(ID_PROJETO) REFERENCES PROJETO(ID_PROJETO)
);