CREATE DATABASE ATIVIDADE9;
USE ATIVIDADE9;

CREATE TABLE PILOTO
(
	ID_PILOTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    NUM_REGISTRO VARCHAR(15) NOT NULL,
    DATA_VALIDADE DATE NOT NULL
);

CREATE TABLE VOO
(
	NUMERO_VOO INT PRIMARY KEY AUTO_INCREMENT,
    HORARIO_PARTIDA TIME NOT NULL,
    HORARIO_CHEGADA TIME NOT NULL,
    LOCAL_PARTIDA VARCHAR(150) NOT NULL,
    LOCAL_DESTINO VARCHAR(150) NOT NULL,
    ID_PILOTO INT NOT NULL,
    FOREIGN KEY(ID_PILOTO) REFERENCES PILOTO(ID_PILOTO)
);

CREATE TABLE CLIENTE
(
	ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(150) NOT NULL,
    TELEFONE VARCHAR(20),
    ENDERECO VARCHAR(150) NOT NULL,
    RG VARCHAR(15) UNIQUE NOT NULL
);

CREATE TABLE CLIENTE_VOO
(
	ID_CLIENTE_VOO INT PRIMARY KEY AUTO_INCREMENT,
    NUMERO_CADEIRA INT NOT NULL,
    QTD_BAGAGEM INT DEFAULT 0,
    NUMERO_VOO INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    FOREIGN KEY(NUMERO_VOO) REFERENCES VOO(NUMERO_VOO),
    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);