CREATE DATABASE DB_BORDADOS;
USE DB_BORDADOS;

CREATE TABLE TB_BORDADOS
(
	ID_BORDADO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_BORDADO VARCHAR(150) NOT NULL,
    LARGURA_CM DECIMAL(10,1),
    ALTURA_CM DECIMAL(10,1),
    NUMERO_PONTOS INT NOT NULL
);

INSERT INTO TB_BORDADOS(NOME_BORDADO, LARGURA_CM, ALTURA_CM, NUMERO_PONTOS)
VALUES
	("Univale - Construindo Conhecimento - 10,0 x 4,8", 10.00, 4.8, 9715),
    ("Administração - 7,5 x 7,7", 7.5, 7.7, 11249),
    ("Odontologia - 10,0 x 8,8", 10.0, 8.8, 20714),
    ("Psicologia - 7,5 x 7,5", 7.5, 7.5, 8164),
    ("Enfermagem - 9,0 x 7,5", 9.0, 7.5, 9204),
    ("Sistemas de Informação - 9,0 x 9,0", 9.0, 9.0, 14497),
    ("Medicina - UFJF GV - Turma V - 9,0 x 10,0 - 20", 9.0, 10.0, 20791),
    ("Pedagogia - 7,0 x 9,0", 7.0, 9.0, 13055);
    
ALTER TABLE TB_BORDADOS RENAME COLUMN NUMERO_PONTOS TO N_PONTO;

ALTER TABLE TB_BORDADOS ADD N_CORES VARCHAR(1);

ALTER TABLE TB_BORDADOS ADD DATA_CRIACAO DATE;

UPDATE TB_BORDADOS SET DATA_CRIACAO = NOW()
WHERE ID_BORDADO < 100; -- Coloquei o where por conta do modo safe

UPDATE TB_BORDADOS SET N_CORES = "5"
WHERE ID_BORDADO = 3 OR ID_BORDADO = 6;

SELECT * FROM TB_BORDADOS
WHERE N_CORES IS NULL;

DELETE FROM TB_BORDADOS
WHERE ID_BORDADO = 8;

SELECT COUNT(ID_BORDADO) AS "QUANT BORDADOS" FROM TB_BORDADOS;

INSERT INTO TB_BORDADOS(NOME_BORDADO, LARGURA_CM, ALTURA_CM, N_PONTO, N_CORES, DATA_CRIACAO)
VALUES
	("Pedagogia - 7,0 x 9,0", 7.0, 9.0, 13055, 5, NOW());
    
SELECT * FROM TB_BORDADOS
WHERE N_PONTO < 10000;

SELECT * FROM TB_BORDADOS
WHERE LARGURA_CM >= 7.5 AND LARGURA_CM <= 9.0;

ALTER TABLE TB_BORDADOS DROP DATA_CRIACAO;

ALTER TABLE TB_BORDADOS MODIFY COLUMN N_CORES INT;

SELECT NOME_BORDADO, (N_PONTO / 1000) * 2.5 AS "VALOR" FROM TB_BORDADOS;

SELECT NOME_BORDADO, N_PONTO FROM TB_BORDADOS
ORDER BY NOME_BORDADO ASC;

SELECT * FROM TB_BORDADOS
ORDER BY LARGURA_CM DESC;

SELECT * FROM TB_BORDADOS
WHERE NOME_BORDADO LIKE "%gia%";

SELECT ID_BORDADO, NOME_BORDADO, LARGURA_CM, ALTURA_CM, N_PONTO + 2000, N_CORES FROM TB_BORDADOS;

UPDATE TB_BORDADOS SET N_CORES = 10
WHERE N_CORES IS NULL AND ID_BORDADO < 100; -- ADCIONEI "AND ID_BORDADO < 100" SO POR CONTO DO MODO SAFE

RENAME TABLE TB_BORDADOS TO TABELA_BORDADOS;

SELECT * FROM TABELA_BORDADOS;