CREATE DATABASE vendas;

USE vendas;

CREATE TABLE cliente (
  IDCLIENTE int AUTO_INCREMENT,
  NOME varchar(100) NOT NULL,
  SOBRENOME varchar(100) DEFAULT NULL,
  DATANASC date DEFAULT NULL,
  CELULAR varchar(11) DEFAULT NULL,
  EMAIL varchar(255) DEFAULT NULL,
  CPF varchar(11) DEFAULT NULL,
  DATACAD datetime DEFAULT NULL,
  ATIVO varchar(1) DEFAULT 'S',
  PRIMARY KEY (IDCLIENTE)
);

CREATE TABLE cliente_enderecos (
  IDENDERECO int AUTO_INCREMENT,
  IDCLIENTE int NOT NULL,
  CEP varchar(7) DEFAULT NULL,
  LOGRADOURO varchar(150) DEFAULT NULL,
  NUMERO int DEFAULT NULL,
  COMPLEMENTO varchar(100) DEFAULT NULL,
  BAIRRO varchar(100) DEFAULT NULL,
  CIDADE varchar(100) DEFAULT NULL,
  ESTADO varchar(100) DEFAULT NULL,
  DATACAD datetime DEFAULT NULL,
  ATIVO varchar(1) DEFAULT 'S',
  PRIMARY KEY(IDENDERECO),
  FOREIGN KEY(IDCLIENTE) REFERENCES cliente(IDCLIENTE)
);

CREATE TABLE empresa (
  IDEMPRESA int AUTO_INCREMENT,
  NOMEFANTASIA varchar(150) NOT NULL,
  RAZAOSOCIAL varchar(150) DEFAULT NULL,
  CNPJ varchar(15) DEFAULT NULL,
  DATACAD datetime DEFAULT NULL,
  ATIVO varchar(1) DEFAULT 'S',
  PRIMARY KEY (IDEMPRESA)
);

CREATE TABLE funcionario (
  IDFUNCIONARIO int AUTO_INCREMENT,
  IDEMPRESA int NOT NULL,
  NOME varchar(100) NOT NULL,
  NOMECOMPLETO varchar(255) DEFAULT NULL,
  CELULAR varchar(11) DEFAULT NULL,
  CPF varchar(11) DEFAULT NULL,
  CARGO varchar(100) DEFAULT NULL,
  CEP varchar(7) DEFAULT NULL,
  DATACAD datetime DEFAULT NULL,
  ATIVO varchar(1) DEFAULT 'S',
  PRIMARY KEY (IDFUNCIONARIO),
  FOREIGN KEY(IDEMPRESA) REFERENCES empresa(IDEMPRESA)
);

CREATE TABLE grupo (
  IDGRUPO int AUTO_INCREMENT,
  NOME varchar(100) NOT NULL,
  DATACAD datetime DEFAULT NULL,
  ATIVO varchar(1) DEFAULT 'S',
  PRIMARY KEY (IDGRUPO)
);

CREATE TABLE produto (
  IDPRODUTO int AUTO_INCREMENT,
  IDGRUPO int NOT NULL,
  NOME varchar(100) NOT NULL,
  DESCRICAO varchar(100) DEFAULT NULL,
  PRECO float DEFAULT NULL,
  DIRIMAGEM varchar(255) DEFAULT NULL,
  DATACAD datetime DEFAULT NULL,
  ATIVO varchar(1) DEFAULT 'S',
  PRIMARY KEY (IDPRODUTO),
  FOREIGN KEY(IDGRUPO) REFERENCES grupo(IDGRUPO)
);

CREATE TABLE venda (
  IDVENDA int AUTO_INCREMENT,
  IDEMPRESA int NOT NULL,
  IDCLIENTE int NOT NULL,
  IDENDERECO int DEFAULT NULL,
  IDFUNCIONARIO int NOT NULL,
  TIPOVENDA varchar(1) DEFAULT NULL,
  VALORPRODUTOS float DEFAULT NULL,
  TAXAENTREGA float DEFAULT NULL,
  TOTALVENDA float DEFAULT NULL,
  DATACAD datetime DEFAULT NULL,
  STATUSVENDA varchar(1) DEFAULT 'N',
  PRIMARY KEY (IDVENDA),
  FOREIGN KEY(IDEMPRESA) REFERENCES empresa(IDEMPRESA),
  FOREIGN KEY(IDCLIENTE) REFERENCES cliente(IDCLIENTE),
  FOREIGN KEY(IDENDERENCO) REFERENCES cliente_enderecos(IDENDERECO),
  FOREIGN KEY(IDFUNCIONARIO) REFERENCES funcionario(IDFUNCIONARIO)
);

CREATE TABLE venda_itens (
  IDVENDAITEM int AUTO_INCREMENT,
  IDITEM int NOT NULL,
  IDVENDA int NOT NULL,
  IDPRODUTO int NOT NULL,
  QTDE FLOAT DEFAULT NULL,
  PRECOVENDA float DEFAULT NULL,
  DATACAD datetime DEFAULT NULL,
  PRIMARY KEY (IDVENDAITEM),
  FOREIGN KEY(IDVENDA) REFERENCES venda(IDVENDA),
  FOREIGN KEY(IDPRODUTO) REFERENCES produto(IDPRODUTO)
);
