CREATE DATABASE DB_SGE;
USE DB_SGE;

CREATE TABLE ALUNO
(
	ID_ALUNO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_ALUNO VARCHAR(150) DEFAULT "SEM NOME"
);

CREATE TABLE CURSOS
(
	ID_CURSOS INT PRIMARY KEY AUTO_INCREMENT,
    CURSO VARCHAR(150) DEFAULT "SEM NOME",
    VALOR DECIMAL(10,2)
);

INSERT INTO ALUNO(NOME_ALUNO)
VALUES
	("João"),
    ("José"),
    ("Isis"),
    ("Theo"),
    ("Pedro"),
    ("Gil");
    
INSERT INTO CURSOS(CURSO, VALOR)
VALUES
	("Design", 900.00),
    ("Sistema deInformação", 900.00),
    ("Odontologia", 1200.00),
    ("Medicina", 6500.00),
    ("Direito", 1300.00),
    ("Engenharia Civil", 1400.00);
    
    
CREATE TABLE ALUNO_CURSOS
(
	ID_ALUNO_CURSO INT PRIMARY KEY AUTO_INCREMENT,
    ID_ALUNO INT NOT NULL,
    ID_CURSOS INT NOT NULL,
    DATA_MATRICULA DATETIME,
    CONSTRAINT FK_ALUNO_CURSOS_ALUNO FOREIGN KEY(ID_ALUNO) REFERENCES ALUNO(ID_ALUNO),
    CONSTRAINT FK_ALUNO_CURSOS_CURSOS FOREIGN KEY(ID_CURSOS) REFERENCES CURSOS(ID_CURSOS)
);

INSERT INTO ALUNO_CURSOS(ID_ALUNO, ID_CURSOS, DATA_MATRICULA)
VALUES
	(1, 5, NOW()),
    (2, 1, NOW()),
    (3, 4, NOW()),
    (6, 3, NOW()),
    (4, 2, NOW()),
    (5, 6, NOW()),
    (4, 6, NOW()),
    (2, 5, NOW()),
    (3, 3, NOW()),
    (5, 5, NOW()),
    (5, 1, NOW());
    
SELECT * FROM ALUNO;

SELECT * FROM CURSOS;

SELECT * FROM ALUNO_CURSOS;
    
SELECT ALUNO.NOME_ALUNO, CURSOS.CURSO FROM ALUNO_CURSOS
INNER JOIN ALUNO
ON ALUNO_CURSOS.ID_ALUNO = ALUNO.ID_ALUNO
INNER JOIN CURSOS
ON ALUNO_CURSOS.ID_CURSOS = CURSOS.ID_CURSOS
ORDER BY ALUNO.NOME_ALUNO ASC;

SELECT ALUNO.NOME_ALUNO, CURSOS.VALOR FROM ALUNO_CURSOS
INNER JOIN ALUNO
ON ALUNO_CURSOS.ID_ALUNO = ALUNO.ID_ALUNO
INNER JOIN CURSOS
ON ALUNO_CURSOS.ID_CURSOS = CURSOS.ID_CURSOS
WHERE CURSOS.VALOR >= 1300.00;

SELECT ALUNO.NOME_ALUNO, COUNT(ALUNO_CURSOS.ID_ALUNO) AS "QUANTIDADE MATRICULAS" FROM ALUNO_CURSOS
INNER JOIN ALUNO
ON ALUNO_CURSOS.ID_ALUNO = ALUNO.ID_ALUNO
WHERE ALUNO_CURSOS.ID_ALUNO = 5;

SELECT ALUNO.NOME_ALUNO, COUNT(ALUNO_CURSOS.ID_ALUNO) AS "QUANTIDADE MATRICULAS" FROM ALUNO_CURSOS
INNER JOIN ALUNO
ON ALUNO_CURSOS.ID_ALUNO = ALUNO.ID_ALUNO
WHERE (ALUNO_CURSOS.ID_ALUNO = 3 OR ALUNO_CURSOS.ID_ALUNO = 4)
GROUP BY(ALUNO.NOME_ALUNO);

SELECT CURSOS.CURSO, COUNT(ALUNO_CURSOS.ID_CURSOS) AS "QUANT ALUNOS" FROM ALUNO_CURSOS
INNER JOIN CURSOS
ON ALUNO_CURSOS.ID_CURSOS = CURSOS.ID_CURSOS
WHERE ALUNO_CURSOS.ID_CURSOS = 5;