USE VENDAS_FOMEDEMAIS;

INSERT INTO EMPRESA(NOMEFANTASIA, RAZAOSOCIAL, CNPJ, DATACAD)
VALUES 
    ("Fome de mais", "Rafael Reis LTDA", "18854410000165", NOW());
    
SELECT * FROM EMPRESA;
    
INSERT INTO FUNCIONARIO(IDEMPRESA, NOME, NOMECOMPLETO, CELULAR, CPF, CARGO, CEP, DATACAD)
VALUES
	(1, "Rafael", "Rafael Reis da Silveira", "33984623987", "02175431622", "Dono", "3503261", NOW());
    
SELECT E.NOMEFANTASIA, F.NOMECOMPLETO, F.CELULAR, F.CARGO, F.DATACAD FROM EMPRESA E
INNER JOIN FUNCIONARIO F
ON E.IDEMPRESA = F.IDEMPRESA;

INSERT INTO CLIENTE(NOME, SOBRENOME, DATANASC, CELULAR, EMAIL, CPF, DATACAD)
VALUES
	("Rafael", "Reis", "1998-03-24 23:59:59", "33984623987", "rafaelreis.12@hotmail.com", "02175431622", NOW());
    
SELECT * FROM CLIENTE;
    
INSERT INTO CLIENTE_ENDERECOS(IDCLIENTE, LOGRADOURO, NUMERO, BAIRRO)
VALUES
	(1, "Rua dos bobos", "0", "Centro"),
    (1, "Rua dos não bobos", "1", "Vila Bretas");
    
SELECT * FROM CLIENTE_ENDERECOS;
    
INSERT INTO GRUPO(NOME, DATACAD)
VALUES
	("LANCHES", NOW()),
    ("BEBIDAS", NOW()),
    ("DRINKS", NOW());
    
SELECT IF(C.SOBRENOME IS NULL, C.NOME, CONCAT(C.NOME, " ", C.SOBRENOME)) AS "NOME COMPLETO", EN.LOGRADOURO, EN.NUMERO, EN.BAIRRO FROM CLIENTE C
INNER JOIN CLIENTE_ENDERECOS EN
ON C.IDCLIENTE = EN.IDCLIENTE;

INSERT INTO PRODUTO(IDGRUPO, NOME, PRECO, DATACAD)
VALUES
	(1, "X-TUDO", 22.00, NOW()),
    (2, "COCA LATA", 7.00, NOW()),
    (3, "CAIPIRINHA", 20.50, NOW());
    
SELECT G.NOME, P.NOME, P.PRECO, P.DATACAD, P.ATIVO FROM PRODUTO P
INNER JOIN GRUPO G
ON G.IDGRUPO = P.IDGRUPO;

INSERT INTO VENDA(IDEMPRESA, IDCLIENTE, IDENDERECO, IDFUNCIONARIO, TIPOVENDA, TOTALVENDA)
VALUES
	(1, 1, 1, 1, "B", 50.00);

SELECT V.IDVENDA, C.NOME AS "NOME CLIENTE", E.NOMEFANTASIA AS "NOME EMPRESA", EN.LOGRADOURO AS "RUA", F.NOME AS "NOME FUNCIONARIO" FROM VENDA V
INNER JOIN CLIENTE C
ON V.IDCLIENTE = C.IDCLIENTE
INNER JOIN EMPRESA E
ON V.IDEMPRESA = E.IDEMPRESA
INNER JOIN CLIENTE_ENDERECOS EN
ON V.IDENDERECO = EN.IDENDERECO
INNER JOIN FUNCIONARIO F
ON V.IDFUNCIONARIO = F.IDFUNCIONARIO;