USE VENDAS_DELIVERY;

SELECT * FROM CLIENTE;
SELECT * FROM CLIENTE_ENDERECOS;
SELECT * FROM FUNCIONARIO;
SELECT * FROM EMPRESA;
SELECT * FROM GRUPO;
SELECT * FROM PRODUTO;
SELECT * FROM VENDA;
SELECT * FROM VENDA_ITENS;

SELECT 
	EMP.NOMEFANTASIA AS "NOME EMPRESA", EMP.LOGRADOURO, EMP.NUMERO,
    IF(C.SOBRENOME IS NULL, C.NOME, CONCAT(C.NOME, C.SOBRENOME)) AS "NOME CLIENTE", C.EMAIL, C.CELULAR,
    ENDE.LOGRADOURO, ENDE.NUMERO,
    F.NOMECOMPLETO AS "NOME FUNCIONARIO"
FROM VENDA V
JOIN EMPRESA EMP
ON V.IDEMPRESA = EMP.IDEMPRESA
JOIN CLIENTE C
ON V.IDCLIENTE = C.IDCLIENTE
JOIN CLIENTE_ENDERECOS ENDE
ON V.IDENDERECO = ENDE.IDENDERECO
JOIN FUNCIONARIO F
ON V.IDFUNCIONARIO = F.IDFUNCIONARIO
WHERE IDVENDA = 3;

SELECT VI.IDITEM, P.NOME AS "NOME PRODUTO",VI.QTDE, VI.PRECOVENDA FROM VENDA_ITENS VI
JOIN VENDA V
ON VI.IDVENDA = V.IDVENDA
JOIN PRODUTO P
ON VI.IDPRODUTO = P.IDPRODUTO
WHERE V.IDVENDA = 3;