/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.bookmanager.Layout;

import com.mycompany.bookmanager.MainMenu.MainClass;
import java.awt.Color;
import java.util.stream.IntStream;

/**
 *
 * @author rafae
 */
public class BooksLayout extends javax.swing.JPanel {

    /**
     * Creates new form Books
     */
    public BooksLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackground = new javax.swing.JPanel();
        jLabelAutor = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanelBackground.setBackground(new java.awt.Color(204, 255, 204));
        jPanelBackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBackgroundMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelBackgroundMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelBackgroundMouseExited(evt);
            }
        });

        jLabelAutor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelAutor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAutor.setText("Autor");
        jLabelAutor.setToolTipText("");
        jLabelAutor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAutorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelAutorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelAutorMouseExited(evt);
            }
        });

        jLabelID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelID.setText("ID");
        jLabelID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIDMouseExited(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("<html> Titulo </html>");
        jLabelTitulo.setToolTipText("");
        jLabelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTituloMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelTituloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTituloMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jLabelID)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelID)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTituloMouseClicked
        BookEdit();
    }//GEN-LAST:event_jLabelTituloMouseClicked
   
    private void jLabelAutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAutorMouseClicked
        BookEdit();
    }//GEN-LAST:event_jLabelAutorMouseClicked

    private void jLabelIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIDMouseClicked
        BookEdit();
    }//GEN-LAST:event_jLabelIDMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        BookEdit();
    }//GEN-LAST:event_formMouseClicked

    private void jLabelTituloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTituloMouseEntered
        jPanelBackground.setBackground(new Color(163, 204, 163));
    }//GEN-LAST:event_jLabelTituloMouseEntered

    private void jLabelTituloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTituloMouseExited
        jPanelBackground.setBackground(new Color(204,255,204));
    }//GEN-LAST:event_jLabelTituloMouseExited

    private void jLabelAutorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAutorMouseEntered
        jPanelBackground.setBackground(new Color(163, 204, 163));
    }//GEN-LAST:event_jLabelAutorMouseEntered

    private void jLabelAutorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAutorMouseExited
        jPanelBackground.setBackground(new Color(204,255,204));
    }//GEN-LAST:event_jLabelAutorMouseExited

    private void jLabelIDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIDMouseEntered
        jPanelBackground.setBackground(new Color(163, 204, 163));
    }//GEN-LAST:event_jLabelIDMouseEntered

    private void jLabelIDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIDMouseExited
        jPanelBackground.setBackground(new Color(204,255,204));
    }//GEN-LAST:event_jLabelIDMouseExited

    private void jPanelBackgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBackgroundMouseClicked
        BookEdit();
    }//GEN-LAST:event_jPanelBackgroundMouseClicked

    private void jPanelBackgroundMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBackgroundMouseEntered
        jPanelBackground.setBackground(new Color(163, 204, 163));
    }//GEN-LAST:event_jPanelBackgroundMouseEntered

    private void jPanelBackgroundMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBackgroundMouseExited
        jPanelBackground.setBackground(new Color(204,255,204));
    }//GEN-LAST:event_jPanelBackgroundMouseExited

    private void BookEdit() {
        MainClass.openEdit = 1;
        MainClass.indexBook = IntStream.range(0, MainClass.books.size()).filter(i -> String.valueOf(MainClass.books.get(i).getID()).equals(jLabelID.getText())).findFirst().orElse(-1);
        AddBooks addBooks = new AddBooks();
        addBooks.show();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabelAutor;
    public javax.swing.JLabel jLabelID;
    public javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelBackground;
    // End of variables declaration//GEN-END:variables
}
